# These are supported funding model platforms

github: amannirala13
patreon: amannirala13
open_collective: amannirala13
ko_fi:  amannirala13
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.paypal.me/amannirala13']
